HERA-Team/hera_mc

Docs/mc_definition.tex, hera_mc/__init__.py, hera_mc/librarian.py, hera_mc/mc.py, hera_mc/mc_session.py, hera_mc/observations.py, hera_mc/rtp.py, hera_mc/server_status.py, hera_mc/temperatures.py, hera_mc/tests/__init__.py, hera_mc/tests/test_connections.py, hera_mc/tests/test_geo_location.py, hera_mc/tests/test_host_status.py, hera_mc/tests/test_librarian.py, hera_mc/tests/test_observations.py, hera_mc/tests/test_rtp.py, hera_mc/tests/test_server_status.py, hera_mc/tests/test_temperatures.py, hera_mc/utils.py
These tables all have add_* and get_* methods and are fully covered by tests. The tables are also documented in docs/mc_definition.tex.
This PR also has some significant code reworking including:
- move MCSession object to it's own file
- define add_* methods on MCSession so add & get methods are on the same object
- define standard time filtering method used by get_* methods on MCSession
- define standard __eq__ and __repr__ methods on MCDeclarativeBase
- __eq__ method supports precision information per column for numeric types. these are defined in the table definition
- changed DOUBLE_PRECISION column types to Float because Float is mapped to DOUBLE PRECISION by default for postgresql
- defined all times in new tables in gps seconds rather than datetimes (this should be propagated to …
=> Add RTP & Librarian tables

hera_mc/host_status.py, hera_mc/mc_session.py, scripts/mc_server_status_daemon.py
Various HERA machines are supposed to periodically report their status to the M&C system. Most of the information can be gathered fairly straightforwardly, but we do want to average load values over time to beat down the noise somewhat. As best I (PKGW) can tell, the most straightforward way to do this is to write a small daemon script that maintains and M&C database connection and does the averaging. Lo and behold, here we are.
We also fix a mistake in mc_session.py.
=> scripts/mc_server_status_daemon.py: add server status reporter

.travis.yml, hera_mc/tests/test_default_db_schema.py, hera_mc/version.py
Make the Travis default database in production mode and use Alembic to create the schema.
Added a test that fails if the alembic revisions don't make the database match the code schema.
=> Set up Travis to use alembic

alembic/versions/93ff199763ac_update_lib_raid_errors_table.py
This is a hotfix for the alembic revision that modified the lib_raid_errors table. I'd like to merge it before the alembic update happens on site.
=> update lib_raid_errors alembic revision to properly add autoincrement

.travis.yml, INSTALL.md, hera_mc/host_status.py, hera_mc/version.py, scripts/mc_server_status_daemon.py
The "psutil" module provides the same functionality and is available in stock Anaconda, whereas "uptime" is not.
=> Remove dependency on "uptime" module

hera_mc/geo_handling.py
This way we can still use hera_mc's database features without needing matplotlib, a very heavyweight dependency, to be installed. This is important if we want things like BeagleBoards to be able to talk to M&C.
=> Only import matplotlib if it's needed

.travis.yml, INSTALL.md, hera_mc/version.py, scripts/mc_megaraid_monitor.py
Part of M&C's job is to check on the status of our RAID arrays. This script uses `storcli64` to assess the RAID status and log it to the database. There is all sorts of information that we *could* log, but hopefully this analysis covers the most important things by watching the event log for errors.
=> scripts/mc_megaraid_monitor.py: script to monitor RAID statuses

scripts/add_connection.py
The add_connection script would always query for the date, which is annoying when you have a script running a couple of hundred times...
=> corrected feature that made running add_connection as a script difficult

hera_mc/tests/test_parts.py, scripts/chk_revisions.py
Just added chk_revisions.py file to check for overlapping part revisions.  To my surprise, it found none.
=> chk_revisions work for overlapping

hera_mc/geo_handling.py, hera_mc/tests/test_geo_location.py
For getting the configuration for RTP, we want to be able to select the `station_type` of the antenna (spec. 'herahex'). This adds the list to the dictionary returned from the `get_cminfo_correlator` function.
=> Update cminfo dictionary

hera_mc/cm_handling.py, hera_mc/tests/test_geo_location.py
This fixes the fact that the get_cm_version method was not actually returning the cm_version as it should have been, and adds tests that would have caught the error.
=> Cm version fix

hera_mc/cm_hookup.py, hera_mc/cm_revisions.py, hera_mc/correlator_levels.py, hera_mc/sys_handling.py, hera_mc/tests/test_sys_handling.py, scripts/hookup.py, scripts/mc_publish_sys_levels.py
This changes hookup to use a local file if it is time-stamped after the latest cm_version table entry.
You can force it to use a new hookup and you can also force it to act as it did previously.
=> Change hookup to use a "local" file to speed it up.

hera_mc/__init__.py, hera_mc/mc_session.py, hera_mc/tests/test_weather.py, hera_mc/weather.py, scripts/mc_wx.py
This one avoids a class that mirrors the whole database in-memory.
It also leverages the existing `mc_wx.py` script to allow the user to filter on start and stop dates and which variables should be printed.
=> Alternate version of "viewwx"

Docs/mc_definition.tex, alembic/versions/c9a1ff35c6ed_make_librarian_file_obsids_optional.py, hera_mc/__init__.py, hera_mc/librarian.py, hera_mc/mc_session.py, hera_mc/tests/test_librarian.py
The Librarian is going to start having some files without obsids, for tracking maintenance files (e.g. weekly database backups) that are not tied to data-taking. M&C should still know about such files, though, so it needs to learn to deal with them.
=> Make the obsids optional on Librarian files.

hera_mc/geo_handling.py
did the thing in the title  'geo.py -g' will make active antennas green and others will be red.
=> made active-antenna geo plots show up in green

hera_mc/cm_table_info.py, hera_mc/cm_transfer.py, scripts/cm_init.py, scripts/cm_pack.py
This gets rid of the confusing _base_ cm option, which was not needed given our new update workflow.
=> Remove base

hera_mc/mc_session.py, hera_mc/tests/test_rtp.py
This is a small tweak to the method to allow for filtering on either task_name or obsid or both.
=> Add support for task_name in get_rtp_task_resource_record

scripts/mc_add_observation.py
This PR uses `aipy` instead of `pyuvdata` to query the metadata necessary for uploading files to the librarian. This is necessary on paper1.
=> Use aipy instead of pyuvdata to query file metadata

hera_mc/sys_handling.py
Right now, the correlator query to M&C info only includes antennas with an `HH` (`herahex`) designation. It should be expanded to include the outriggers `HA` and `HB` (`heraringa` and `heraringb`).
=> Update correlator cminfo query to include outriggers

hera_mc/sys_handling.py
Caused the 2-minutely cronjob to crash.
=> hera_mc/sys_handling.py: fix bug in Handling.publish_summary()

hera_mc/node.py, hera_mc/tests/test_node.py
The function is only called on site, so this was missed in the Travis checks.
=> fix bug from rename of get_node_list function

hera_mc/mc_session.py, hera_mc/tests/test_librarian.py, hera_mc/tests/test_node.py, hera_mc/tests/test_observations.py, hera_mc/tests/test_rtp.py, hera_mc/tests/test_server_status.py, hera_mc/tests/test_subsystem_error.py, hera_mc/tests/test_weather.py
Add an option to `ms_session._time_filter` to get the most recent entry. Propagate that option to get methods on mc_session that use it and add tests.
I realized the need for this while writing the correlator control code, but did it in another branch to keep the PRs organized.
=> Add most_recent filter

scripts/mc_add_observation.py
Before the librarian will accept observations, they must be known to the M&C system. This PR updates the `mc_add_observation.py` script to be compatible with uvh5 files.
=> Update script for adding observations to librarian

hera_mc/cm_health.py, hera_mc/tests/test_connections.py
When I updated the hookup and pulled it back down, the overlap checker found overlaps that just shared an end point (we don't want it to find contiguous but non-overlapping ones).  It did not flag those earlier, which I find very confusing since it did not relate to any new connection.  I've rewritten the overlap checker to fix that (and made it more "elegant").
=> updated the overlap checker

hera_mc/mc_session.py
Permissions issues happen when the monitoring daemon calls the code that writes the config file out to save it to the Librarian. Fix it to write the file to /tmp to avoid the permissions issue (the file is deleted automatically, so /tmp is a reasonable place).
=> Fix writing librarian files -- write to /tmp to avoid permissions issues

alembic/versions/d208118c58d0_add_ant_status_table.py, hera_mc/correlator.py, hera_mc/mc_session.py, hera_mc/tests/test_correlator.py, scripts/mc_monitor_correlator.py
To track the antenna status as reported in the correlator redis database (from the SNAPs).
=> Add antenna status table

hera_mc/cm_hookup.py
numpy 1.16.3 changed the defaulting of `allow_pickle` from True to False. This PR adds `allow_pickle=True` where required for cm_hookup
=> fix numpy.load calls for change in allow_pickle default

scripts/hookup.py
The hookup script had an errant underscore character.
=> fixed hookup script

hera_mc/__init__.py, hera_mc/mc_session.py, hera_mc/tests/test_subsystem_error.py
Add a `testing` boolean keyword. If set to True, the object will be returned rather than added to the database.
=> Add a test mode for subsystem_error creation

scripts/mc_server_status_daemon.py
The server status daemon script for collecting host info on site was not python3 compatible (because it explicitly used long integers). Using `from builtins import int` on python2 makes `int` a subclass of `long`, which allows for python2/3 compatible code. This change is necessary once we transition to using a python3 environment on-site. It's not clear to me if the careful handling of 32-bit integers is still necessary (perhaps `psutil` has transitioned to using 64-bit integers internally), but better safe than sorry.
=> Make server status daemon script py3 compatible

.travis.yml, hera_mc/autocorrelations.py, hera_mc/server_status.py, hera_mc/tests/test_autocorrelations.py
plotly is moving to use `chart_studio` for the plotly call. We will need to install this package on the executing computer too. 
available on [conda with custom channel](https://anaconda.org/plotly/chart-studio) or pip
see https://plot.ly/python/getting-started-with-chart-studio/
=> update to use chart_studio for plotly ploting

scripts/add_rtp_process_event.py
This PR adds a command-line function for adding RTP process events to M&C. This script will be called by the wrapper scripts in `hera_opm` to mark when files are queued/start processing/finish or error.
=> Add script for adding RTP process events

hera_mc/tests/conftest.py, hera_mc/tests/test_librarian.py, hera_mc/tests/test_rtp.py, hera_mc/tests/test_utils.py
This PR allows for tests to pass even if the IERS tables cannot be downloaded. In many places, the dummy time chosen for adding things to the database was "now". Unfortunately, it seems as though astropy cannot extrapolate from the historical tables it ships with. Any tests that rely on astropy time objects were modified to be suitably far in the past that IERS would issue a warning instead of raising an error.
Once this is merged in, the branches in #410 and #414 will need rebasing.
=> Make tests robust to IERS unavailability

hera_mc/mc_session.py, hera_mc/qm.py, hera_mc/tests/test_qm.py
allows AntMetrics pols to be 'n' and 'e' as well as 'x' and 'y' 
also splits up one very long test of errors into individual tests
closes #396
=> Add ne pols

scripts/add_rtp_process_record.py
casts the obsid in add_rtp_process_record to expected format. int(floor( time in gps seconds))
=> Fix RTPProcessRecord script

scripts/correlator_control.py
Since it is a store_true flag, it should default
to False.
=> Remove default True to lsttrig command line option

scripts/mc_megaraid_monitor.py
The script that checks the megaraid status of the pots didn't work in python3. Now it does.
=> Make megaraid script py3 compatible

scripts/correlator_control.py
Currently un-typed in the argument parser, acclen is cast as a string but is later compared against being an int and will always fail this check.
=> Give acclen_spectra Int type

Docs/time_conversion_function
added an overloaded gps2epoch for bigint types. Should really look into making an sqlalchemy version so these could be re-added if we need automatically.
=> update time_conversion doc

hera_mc/correlator.py, hera_mc/tests/test_correlator.py
The correlator is reporting an 'Unknown mode' for a fem_switch value, which it should not be doing but we should handle that kind of thing without falling over.
=> be more robust against fem_switch values from the correlator

hera_mc/cm_active.py, hera_mc/tests/test_sysutils.py, scripts/hookup.py
This had a subtle and vexing error when reading the active data multiple times.  It also had a time-boundary problem for active parts.  This was found because I have been adding more comprehensive checking.  I've also removed the user-run checks in the interest to make the code more maintainable (there was no remaining reason to keep the check flag within hookup.py).
=> fixed connection issue and removed user-run check

hera_mc/autocorrelations.py, hera_mc/cm_dossier.py, hera_mc/cm_hookup.py, hera_mc/cm_sysutils.py, hera_mc/tests/test_sysutils.py
The cm_sysutils methods for get_fully_connected_XXX (and therefore the cminfo method) was very inefficient and unnecessarily looped several times over stations.  Being slow was hampering the correlator.  This fixes that.  Two interfaces changed:
get_all_fully_connected_at_date --> get_connected_stations
the object lost the 'started'/'stopped' attributes for a more general 'timing' attribute
I've changed instances in the repo, but I don't know if any other repo uses these (although I strongly doubt that they do).
=> Cminfo redux:  Updates the cminfo and fully connected station to new faster version

ci/tests.yaml, hera_mc/cm_handling.py, hera_mc/geo_handling.py, hera_mc/tests/test_geo_location.py
Changes a few filter calls in queries. Two change queries to use the class variable first (complained if the desired value came first in python 3.8 for some reason).
The third uses a `<=` opposed to `<` when comparing times for the version query. This was a necessary addition in python 3.8 to get a result. I'm am not sure _why_ it was like this though.
Changed one test into a parametrize which was failing in python 3.8 to identify exactly what was causing the error.
=> Update sqlalchemy filter logic

hera_mc/cm_partconnect.py, hera_mc/tests/test_sysutils.py, scripts/update_apriori.py
Adds statuses and closes #448 
Keeps old arpiori status values for backwards compatibility but sends a DeprecationWarning if one is set.
=> Adds new apriori Statuses

ci/install_conda.sh, ci/tests.yaml
Grabs `pyqt` from `conda-forge` the mains channel is having a `sip` versioning issue on some machines, most notably the vms that github actions uses.
We should monitor pyqt on the main channel to remove the workaround.
=> Fix 3.8 tests

scripts/add_rtp_process_record.py
This PR includes changes to handle pyuvdata's new versioning scheme built on `setuptools_scm`. Before we were calling `pyuvdata.version.construct_version_info()`, but this module and function have been removed. The git information is now available in the `__version__` tag of pyuvdata, except in the case that a tagged/released version is installed. In that case, we retrieve the git hash from GitHub directly.
~I'll test this on site and make sure it behaves as expected. I'll push any necessary changes to this branch.~ This has been tested on site and seems to work.
=> Make changes to script to handle pyuvdata's new versioning scheme

hera_mc/cm_redis_corr.py, hera_mc/cm_sysutils.py, hera_mc/correlator.py, hera_mc/tests/test_sysutils.py
For paper_gpu we need to add correlator_inputs to redis.  I also "harmonized" plural on alts and took out a few cminfo lists that don't get used anywhere.
=> Harmonize cminfo

hera_mc/tests/test_autocorrelations.py
The tests are failing on master because they're using a newer flake8 version that's catching new things. This fixes them.
=> Fix linking for new flake8 version

alembic/versions/c4c88519fb71_fft_overflow.py, hera_mc/correlator.py, hera_mc/mc_session.py, hera_mc/tests/test_correlator.py
This can't be merged until the corresponding PR on `hera_corr_cm` is merged (https://github.com/HERA-Team/hera_corr_cm/pull/42)
=> Add an fft_overflow column to the antenna status table

hera_mc/mc_session.py
removes the check against `hera_corr_cm.ERROR` when trying to calling `take_data` via `correlator_control.py`. Corr_cm now uses just True and False states instead of ERROR/OK
=> Remove hera_corr_cm.ERROR check

scripts/mc_add_observation.py
The script for adding observations to M&C used to import aipy, because it was flexible enough for miriad or uvh5 files. Now that we're uvh5-only, we can drop the aipy requirement.
=> Remove aipy from mc_add_observation.py

hera_mc/cm_partconnect.py, hera_mc/cm_utils.py, hera_mc/data/test_data/initialization_data_part_rosetta.csv, hera_mc/tests/test_parts.py, scripts/update_part_rosetta.py
The earlier "add_rosetta" wasn't fully thought out with the late change to adding timed entries.  This redoes is a la apriori_antenna.  The change allows it to more easily be used in the cm_db_updates workflow.
=> change to update rosetta

hera_mc/cm_hookup.py, hera_mc/cm_sysdef.py, hera_mc/cm_sysutils.py, hera_mc/tests/test_sysutils.py, scripts/dossier.py
This adds useful node functionality to the dossier.py to leave off an argument to get all active nodes.  It also fixes a bug that cropped up in cm_hookup.  Typing `dossier.py node` gives a table of connections, MACs, IPs, and connected antennas etc.
=> this improves the node dossier function and fixes a hookup bug

hera_mc/cm_utils.py, hera_mc/tests/test_cm_utils.py, scripts/dossier.py
This implements what I had intended to do earlier (and included in the help) to allow nodes to be specified by just integers rather than node hpn in the 'dossier.py' node script.
=> added using ints for dossier node

hera_mc/tests/test_sysutils.py, hera_mc/watch_dog.py
This was going to be a bigger PR to add some other watch dogs that I think are somewhat deprecated in the new scheme.  However, I did want to keep the "mail" method broken out from the initial, so this is to do that.
=> split send-email

scripts/wd_node_temp.py
I had changed a keyword in the watch-dog script somewhere along the line which only reared its head when installed on site...
=> fixed changed arg in wd script

hera_mc/mc_session.py
This fixes a bug that was caused by copy/paste errors when changing the imports in `mc_session.py` in PR #518. This part of the code is control code, so it is not covered by tests either on CI or onsite so was only caught from cronjob errors.
=> fix accidental nodeControl reference change

hera_mc/mc_session.py, hera_mc/qm.py, hera_mc/tests/test_qm.py
This fixes an error that was coming up in RTP at this step: https://github.com/HERA-Team/hera_pipelines/blob/093a43bccf5bc5a41003fbb8710c37cd6f79a59f/pipelines/h4c/rtp/v1/stage_1_task_scripts/do_ANT_METRICS.sh#L64
Here's the `pdb`:
```
(RTP) obs@qmaster:~/rtp_makeflow/2459271$ python -m pdb /home/obs/anaconda/envs/RTP/bin/add_qm_metrics.py --type=ant /mnt/sn1/zen.2459271.50303.sum.ant_metrics.hdf5
> /home/obs/anaconda/envs/RTP/bin/add_qm_metrics.py(8)<module>()
-> """
(Pdb) c
Traceback (most recent call last):
File "/home/obs/anaconda/envs/RTP/lib/python3.7/pdb.py", line 1699, in main
pdb._runscript(mainpyfile)
File "/home/obs/anaconda/envs/RTP/lib/python3.7/pdb.py", line 1568, in _runscript
self.run(statement)
File "/home/obs/anaconda/envs/RTP/lib/python3.7/bdb.py", line 578, in run …
```
=> Allow jones-pol strings (Jnn and Jee) to be used for ingesting ant_metrics

hera_mc/geo_sysdef.py, hera_mc/tests/test_geo_location.py, scripts/cm_region.py
This adds code to return the "region" of an antenna or antenna list.  The regions are [N, E, W] for the core antennas and [A, B] for the outriggers (A is the inner ring, B the outer).  Query inputs can be 123, '123', 'HH123', 'A123', etc. If given a list it returns a list, else it returns a string.  If given a part name ('HA325') for an outrigger antenna it will check the prefix and issue a warning if not in agreement.
=> Get region

hera_mc/mc_session.py, hera_mc/tests/test_qm.py
To prevent errors when RTP is re-run.
@jsdillon reported that re-running RTP resulted in the error pasted below. This PR should fix this problem.
```
add_qm_metrics.py --type=ant /mnt/sn1/2459289/zen.2459289.27658.sum.ant_metrics.hdf5
Traceback (most recent call last):
File "/home/obs/anaconda/envs/RTP/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1257, in _execute_context
cursor, statement, parameters, context
File "/home/obs/anaconda/envs/RTP/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 898, in do_executemany
cursor.executemany(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ant_metrics_pkey"
DETAIL:  Key (obsid, ant, pol, metric)=(1299868709, 0, jee, ant_metrics_corr) already exists. …
```
=> Allow for updates to qm metric tables

hera_mc/cm_redis_corr.py, hera_mc/cm_sysutils.py, hera_mc/tests/test_sysutils.py
This changes the way the snap cm info get passed to the correlator to only use the heraNodeNSnapM format (rather than the SNP serial number).
=> Cminfo improve

.github/.codecov.yml, hera_mc/mc_session.py, scripts/add_rtp_process_event.py
The add process event calls in the script where using incorrect keywords when trying to call mc_session methods.
=> Line up process event api

scripts/mc_launch_rtp.py
Changes the tmux launching command to explicitly source obs's bashrc. 
this allows us to just use conda (de)-activate calls.
changed the default shell to /bin/bash in .tmux.conf file on site.
=> Update rtp launch command

scripts/mc_launch_rtp.py
This is a quick PR to increase the number of jobs that RTP runs from the default (30) to 100.
=> Launch more RTP jobs

hera_mc/cm_utils.py
Make a trivial change to extend the time bounds of get_astropytime so that old queries don't issue warning
=> change get_astropytime bounds

scripts/add_rtp_task_resource_records.py
I've added a new script to the scripts directory which looks for any entries in RTPTaskJobID (RTPTaskMultipleJobID) that don't exist in RTPTaskResourceRecord (RTPTaskMultipleResourceRecord).  The SLURM JobIDs associated with these entries are used to query the SLURM database and populate the corresponding RTP task resource tables with SLURM compute info.
I don't know if there are any code style / pre-commit requirements for hera_mc so let me know if anything (including syntax, filename, etc.) need to be changed.
=> Add script to update RTP task resource tables

.github/workflows/testsuite.yml
Now that we have a hook to pre-commit.ci as part of our CI, we don't need to run a separate linting job. This PR removes it from the series of GitHub actions.
Previously we were running our linting jobs as a GitHub action. We don't need to do this anymore.
=> Remove linting job from workflow

CHANGELOG.md, hera_mc/cm_active.py, hera_mc/cm_hookup.py, hera_mc/cm_partconnect.py, hera_mc/cm_redis_corr.py, hera_mc/cm_revisions.py, hera_mc/cm_sysutils.py, hera_mc/cm_transfer.py, hera_mc/geo_handling.py, hera_mc/geo_location.py, hera_mc/mc.py, hera_mc/tests/test_cm_transfer.py, hera_mc/tests/test_connections.py, hera_mc/tests/test_geo_location.py, hera_mc/watch_dog.py
All calls for an external session are now handled through MCSessionWrapper
Database sessions from within configuration management are handled by either passing a session or by passing None, whereby a new session was started.  This led to a cumbersome set of statements and a `close_session_when_done` flag.  This PR sets up a new session wrapper to handle all of that in a much cleaner fashion.
The cleans up the code and also makes it much safer in terms of closing sessions appropriate.  It also incorporates the testing flag.
Other:
=> Update session handler

scripts/add_rtp_process_record.py
@jsdillon noticed that RTP is failing now that we switched all the repos to `setuptools_scm`. I updated the `add_rtp_process_record` to treat everything like how pyuvdata was parsed before.
=> update rtp process record to be compatible with scm

hera_mc/mc.py
When the session wrapper closed, the return was being printed to my screen, which caused extraneous print statements.  I added an underscore to catch the return of the module to remove the extraneous print statement to my screen.
Gets rid of annoying and non-illuminating printed lines.
Other:
- [x ] My code follows the code style of this project.
=> add a catcher variable to wrapper session close

scripts/mc_monitor_correlator.py
This should have been included in #616, it makes the daemon actually get the `snap_feng_init_status` out of redis and put it in M&C.
Other:
=> Add the SNAP feng_init status to the monitoring daemon

scripts/hera_mini_snap_data_catcher.py
Organizes the mini-snap catcher to write data to folders based on the JD.
Tried to sure up some logic to reduce the amount of logger warnings about data timeouts.
On site verified that data is written to the expected folders but haven't verified the logger is any less talkative yet (currently taking data at time of writing).
=> Mini snap make folders

scripts/mc_rtp_launch_record.py
When adding data files to the M&C tables for RTP, we need to know where to find these files on disk. In particular, there are in principle two different storage nodes for data to end up. Previously we were always running this script from the storage nodes. Now, we are calling this from the RTP execution hosts as part of the file conversion process, so the `hostname` command does not give the result it did previously. This change has been deployed to site and seems to be working.
Fixes a bug observed onsite where the prefix was recorded as `unknown`, which then meant that RTP failed to launch correctly.
=> Fix how prefix directory is handled when adding files to RTP

scripts/hera_mini_snap_data_catcher.py
Adds a `tag` to the data in the extra_keywords. This tag is required for adding the observations to M&C which is itself required to add them to the librarian.
=> Update Snap Auto catcher

CHANGELOG.md, hera_mc/mc_session.py, hera_mc/tests/test_correlator.py
Currently it is easy to get the next entry after a point in time or the most recent entry as of the current time, but it is hard to get the last entry before a point in time (the most recent as of that time). This PR improves the time filter logic that nearly all the real time db getter methods use to enable getting the most recent entry in a table as of a time in the past.
This came up recently as an issue in the daily notebooks. I put in a work around, but this will simplify the logic there and for other users.
=> Better time filtering to allow for getting the most recent table entry as of a time in the past

hera_mc/correlator.py, hera_mc/tests/test_correlator.py, setup.cfg
Fix a bug in getting the correlator file eod info from redis: the jd and status values are strings and need to be converted to ints.
Fixes a bug in #644 
=> properly convert strings to ints from redis for file_eod table

alembic/env.py
Use a solution out of the Alembic cookbook to prevent Alembic from dropping existing tables onsite.
Fixes #590
Other:
I don't think we need to test this onsite or update the changelog.
=> Prevent alembic autogenerate from dropping deleted tables

scripts/mc_launch_rtp_daemon.py
This PR adds a step in the RTP launch script as a last-ditch backstop for fileconversion. Over the past week, I've noticed a least three different nights where one or a handful of files fail to convert (often the .diff or .sum but not the other). This script finds those unconverted files and tries one last time to convert them before launching RTP. 
This PR also adds deletion of .dat files that have been successfully converted. This is useful for saving space on /mnt/sn1 in the case where RTP gets backed up (since .dat files are roughly double the size of .uvh5 files)
=> Add a backstop to file conversion before launching RTP

scripts/hera_mini_snap_data_catcher.py
needed to also change the order some meta-data was generated before and missed it.
definitely works now
```bash
2024-03-19 21:57:41.133 INFO - hera_mini_snap_data_catcher: Starting HERA snap mini data catcher.
2024-03-19 21:57:41.137 INFO - hera_mini_snap_data_catcher: HERA CorrCM Redis connection established.
2024-03-19 21:57:41.143 INFO - hera_mini_snap_data_catcher: Beginning data catching.
WARNING: TimeDeltaMissingUnitWarning: Numerical value without unit or explicit format passed to TimeDelta, assuming days [astropy.time.core]
2024-03-19 21:58:11.809 WARNING - logger: TimeDeltaMissingUnitWarning: Numerical value without unit or explicit format passed to TimeDelta, assuming days
2024-03-19 22:00:14.780 INFO - hera_mini_snap_data_catcher: Writing output file …
```
=> change the order metadata is filled in by helper functions

docs/site_operations.md, hera_mc/observations.py, hera_mc/tests/test_observations.py, hera_mc/utils.py
Update the site docs to list the cask machines as ones that should have their services restarted when hera_mc changes.
Also fixed some astropy future warnings that are new as of astropy 6.1.
Other:
=> Update site ops docs
