HERA-Team/hera_mc

- hera_mc/cm_handling.py
- hera_mc/cm_hookup.py
Small changes to make cm parts work for now.
> Cm handling hookup fix

- Deprecated/renumber_ants.py
- Deprecated/stop_all_C7.py
- hera_mc/cm_transfer.py
- hera_mc/geo_handling.py
- hera_mc/mc_session.py
- hera_mc/observations.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_geo_location.py
- hera_mc/tests/test_librarian.py
- hera_mc/tests/test_observations.py
- hera_mc/tests/test_rtp.py
- scripts/add_station.py
- scripts/cm_init.py
- scripts/cm_pack.py
- scripts/geo.py
- scripts/mc_initialize_db.py
- scripts/move_paper_feed.py
- scripts/write_antenna_location_file.py
Fixes many tests that break otherwise if the default_db is not in testing mode.
Also fixed a few bugs to make write_antenna_location_file.py work.
> Fix geo_handling and cm_transfer to take sessions rather than args

- alembic/versions/93ff199763ac_update_lib_raid_errors_table.py
- hera_mc/__init__.py
- hera_mc/librarian.py
- hera_mc/tests/test_librarian.py
Added a new id column to lib_raid_errors table as the primary key, updated tests & created new Alembic revision file.
> update lib_raid_errors table

- INSTALL.md
They may be really simple, but these are the notes I wish I had when I first installed.
> Details for Mac OS X installation

- hera_mc/cm_handling.py
- hera_mc/cm_hookup.py
- hera_mc/cm_revisions.py
- hera_mc/cm_utils.py
- hera_mc/part_connect.py
- hera_mc/tests/test_geo_location.py
- hera_mc/tests/test_parts.py
- scripts/add_connection.py
- scripts/add_part.py
- scripts/pam_swap.py
This mostly adds a generic add_part and add_connection script, but it does clean up a few uglies in the connection stuff.  I added some tests as well.
> Cm add part

- hera_mc/cm_handling.py
- hera_mc/cm_utils.py
- hera_mc/part_connect.py
- scripts/add_connection.py
I need the stop_connection script to update the data hookups from Matt.  And, as always, this allowed CQI to happen (i.e. some bug fixes).
> implemented stop connection and a few minor bug fixes in add

- scripts/stop_connection.py
Somewhat embarrassingly I had forgotten to add the actual script to the commit...
Everything is the same, except stop_connection.py script has been added.
> I had forgotten to actually add the script!

- scripts/add_connection.py
Fixed the test for validity to allow a connection to be added.
> Fix add conn

- hera_mc/part_connect.py
- scripts/stop_connection.py
Sorry - i thought I had tested it, but the actual db changes choked.
> fixed stupid error in stop connection

- hera_mc/cm_hookup.py
- hera_mc/cm_utils.py
This fixes hookup (even gets rid of the "messy" method!!) and adds full hookup start/time times, which will be used to fix how antennas are viewed as "active" (or "connected" -- we are going to specifically call the full thing "sky-ready").
> Cm fix hookup

- hera_mc/cm_handling.py
- hera_mc/cm_utils.py
- scripts/parts.py
This useful function had broken.  Invoked by parts.py -t
> Fixed the show part types method

- hera_mc/part_connect.py
- scripts/stop_part.py
I need this script and method to fix up the database for some parts which should be shutdown
> made generic stop_part function

- hera_mc/cm_handling.py
- hera_mc/cm_hookup.py
- hera_mc/cm_utils.py
- hera_mc/part_connect.py
Fixed up a few bugs in connections and hookups
> Tweak conn

- hera_mc/cm_handling.py
- hera_mc/cm_revisions.py
- hera_mc/part_connect.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_parts.py
Fixed my testing errors and implemented a few new tests.
> Cm test cover

- scripts/fem_swap.py
Just fixed a script to add new fems based on new cm_hookup inputs
> fixed fem_swap script

- alembic/versions/c0985153bf41_add_cm_version_table.py
- hera_mc/__init__.py
- hera_mc/cm_handling.py
- hera_mc/cm_transfer.py
- hera_mc/cm_utils.py
- hera_mc/geo_handling.py
This branch adds a table to track the cm_version in the M&C database and uses that table as the source of the cm git hash as appropriate.
> cm version

- hera_mc/cm_hookup.py
As the comment says, I forgot to make the queries in cm_hookup case-insensitive.
> forgot to make cm_hookup case-insensitive

- hera_mc/cm_transfer.py
- scripts/cm_pack.py
- scripts/geo.py
Added the git hash versioning thing for db updates.
> Versioning

- scripts/write_antenna_location_file.py
This changes the way that cm_version information is retrieved. Script works on-site
> Script update

- hera_mc/cm_hookup.py
- hera_mc/part_connect.py
- scripts/add_connection.py
- scripts/fem_swap.py
This small update is needed to allow updating of the database using current scripts.
> Fix scripts

- scripts/add_part.py
> fixed add-part

- hera_mc/cm_hookup.py
- hera_mc/part_connect.py
- scripts/fem_swap.py
- scripts/parts.py
removes the double entries (for most, but at least the remaining aren't confusing)
> fixed (most) of the hookup squirreliness

- hera_mc/cm_handling.py
- hera_mc/part_connect.py
- hera_mc/tests/test_parts.py
- scripts/part_info.py
Now that we have failing parts I need to add to the part_info table.
> added function and script to add part comments to part_info

- hera_mc/cm_hookup.py
- hera_mc/tests/test_qm.py
- scripts/parts.py
> added the show-ports and show-revs option for hookup

- hera_mc/server_status.py
- scripts/mc_update_plotly_plots.py
Exercise for reader: write analogous code to plot load averages on the still machines.
> Resume plotting Librarian machine uptimes on plotly

- hera_mc/geo_location.py
- scripts/add_station.py
This needed to be fixed to add the new stations.
> fixed add_station, which meant fixing geo_location.update

- Deprecated/pam_swap.py
- hera_mc/cm_transfer.py
- hera_mc/cm_utils.py
- scripts/part_info.py
- scripts/parts.py
Small number of small random things...
> Fix pam swap

- hera_mc/cm_hookup.py
- hera_mc/cm_transfer.py
- hera_mc/cm_utils.py
- hera_mc/correlator_levels.py
- hera_mc/sys_handling.py
- hera_mc/tests/test_sys_handling.py
- scripts/mc_publish_sys_levels.py
- scripts/online_roach_powers.py
- scripts/parts.py
> added html stuff for sys_handling

- hera_mc/cm_dataview.py
- hera_mc/cm_hookup.py
- hera_mc/cm_revisions.py
- hera_mc/correlator_levels.py
- hera_mc/sys_handling.py
- hera_mc/tests/test_dataview.py
- hera_mc/tests/test_sys_handling.py
This just adds a "library" file so that repeated calls don't need to read in the file every time.  Two comments:
(1) arguably the "intelligence" should be in the show, not the dictionary (but that is not how it is...)
(2) do I need the copy.copy s
> added the hookup_dict_library thing

- Deprecated/move_paper_feed.py
- INSTALL.md
- hera_mc/cm_dataview.py
- hera_mc/cm_handling.py
- hera_mc/cm_hookup.py
- hera_mc/cm_revisions.py
- hera_mc/cm_transfer.py
- hera_mc/cm_utils.py
- hera_mc/geo_handling.py
- hera_mc/geo_location.py
- hera_mc/part_connect.py
- hera_mc/sys_handling.py
- hera_mc/tests/test_parts.py
- hera_mc/tests/test_sys_handling.py
- scripts/add_connection.py
- scripts/add_part.py
- scripts/add_station.py
- scripts/cmdv.py
- scripts/geo.py
- scripts/hookup.py
- scripts/mc_gps.py
- scripts/mc_part_info.py
- scripts/parts.py
- scripts/stop_connection.py
- scripts/stop_part.py
This has exactly one line of actual fixing of a problem (in put_keys_in_numerical_order) and the rest is gratuitous fixing of what I call my 'single-underscore period'.
> Query key fix

- hera_mc/mc_session.py
- scripts/mc_monitor_roach_temps.py
This is being tested on-site and so far seems to work.
Closes #189.
> scripts/mc_monitor_roach_temps.py: add ROACH monitor

- hera_mc/cm_hookup.py
- hera_mc/tests/test_sys_handling.py
- scripts/hookup.py
I don't know why this one passes unit testing and the other one didn't but, ...
> Redo of hookup diagnostics for RTP

- hera_mc/cm_hookup.py
This adds logging the last possible date that could make the checks for the cache file...
> Addl hookup

- hera_mc/cm_dataview.py
- hera_mc/cm_hookup.py
- hera_mc/cm_revisions.py
- hera_mc/geo_handling.py
- scripts/geo.py
> trying to repair cache file issue PLEASE MERGE

- hera_mc/cm_hookup.py
- scripts/hookup.py
- scripts/parts.py
This includes antenna counts as a hookup flag, to see how many antennas are there etc.  It also fixes a bad fail when a part number isn't supplied for parts.py
> Hookupinfo

- hera_mc/geo_handling.py
pkgw had pointed it out, but I hadn't even realized I had unburied pet
> buried plt again

- hera_mc/geo_handling.py
- scripts/geo.py
The good idea to have an external "default" station_types didn't quite work in the geo script... This is fixed.
> fixed geo plot

- hera_mc/geo_handling.py
- scripts/cm_syslog.py
> fixed error on displaying ant geo

- hera_mc/cm_handling.py
- hera_mc/cm_hookup.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_parts.py
- scripts/parts.py
Make part/connection dossiers separate classes.
> Dossier class

- hera_mc/cm_hookup.py
- hera_mc/part_connect.py
silly small oversight...  also set a specified order for which epoch the parts comprise
> fixed hookup table error on last part in chain

- .travis.yml
- hera_mc/tests/test_qm.py
disabled qm testing for python 3 until it is compatible
fixes #229
> start testing against python 3

- hera_mc/cm_transfer.py
- hera_mc/sys_handling.py
- hera_mc/tests/__init__.py
- hera_mc/tests/test_db_check.py
- hera_mc/tests/test_geo_location.py
- scripts/cm_init.py
This is fixes all tests onsite except for the tests associated with roach_temperatures, which are deprecated in PR #239 
fixes #188
> Fix onsite tests

- hera_mc/cm_handling.py
all other printout lists except connections were sorted - now so are connections
> sorted connection printout

- hera_mc/cm_dataview.py
- hera_mc/cm_utils.py
- hera_mc/tests/test_dataview.py
- scripts/cmdv.py
- scripts/hookup.py
This is a start to getting commissioning their antenna list.  It includes julian date in the cm_utils.get_astropytime function.
> Added cm_dataview to get antenna info over time.  Included julian date as option.

- INSTALL.md
- hera_mc/cm_utils.py
- scripts/add_connection.py
- scripts/add_part.py
- scripts/add_part_info.py
- scripts/add_station.py
- scripts/cm_syslog.py
- scripts/stop_connection.py
- scripts/stop_part.py
raw_input no longer works for Python 3.
> changed raw_input to six.moves.input and slight update to install

- hera_mc/cm_hookup.py
Made to be compatible with both python2 and python3
> make 2 hookup cache depending on python version

- .travis.yml
add h5py to Travis conda installation for qm code
> Fix Travis environment

- .travis.yml
Improve the accuracy of the coveralls report now that we're building against python 2 & 3.
> Update .travis.yaml to add parallel build support for coveralls

- hera_mc/mc_session.py
- hera_mc/tests/test_node.py
- scripts/node_power_control.py
minor improvements to the error message for the `node_power_control` script.
> better error messages for node control script

- hera_mc/part_connect.py
- hera_mc/sys_handling.py
cminfo failed if only one pol was hooked up.
> fixed error is only one pol is hooked up

- .travis.yml
- hera_mc/tests/test_librarian.py
update travis pep8 check to catch errors in test code, fix pep8 issues in test code
> Pep8 fixes

- alembic/versions/9460cc78cb50_add_correlator_control.py
- hera_mc/__init__.py
- hera_mc/correlator.py
- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_node.py
- hera_mc/tests/test_weather.py
- scripts/correlator_control.py
- scripts/mc_monitor_correlator.py
- scripts/test_cover_noinstall.sh
> Correlator command interface

- scripts/hookup.py
Defaulted -p to HH,HA,HB (in cm_utils)
> changed hookup default parameter

- hera_mc/correlator.py
> Fix correlator monitor code

- hera_mc/cm_hookup.py
- hera_mc/cm_utils.py
- hera_mc/part_connect.py
- hera_mc/sys_handling.py
- hera_mc/tests/test_sys_handling.py
- scripts/mc_publish_summary.py
This allows for the hookup to be published on Hera.today
> Publish hookup

- hera_mc/geo_handling.py
- hera_mc/tests/test_geo_location.py
- scripts/geo.py
Found this when trying to reconcile cm and the site google sheet.
> fixed installed antennas not writing to file and added some tests

- INSTALL.md
- scripts/add_station.py
just a few notes in the install doc based on reinstalling Postgres
> Install doc

- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
Fix a few bugs that were preventing configs from being recorded properly in M&C
> Fix config monitor

- scripts/correlator_control.py
Seems to work now (using the dryrun option)
> Fix (more) bugs in correlator control script

- hera_mc/cm_health.py
- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
pycodestyle added a new test for overindenting which caught a few new things.
> overindent fixes for pep8

- hera_mc/cm_handling.py
- hera_mc/cm_utils.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_parts.py
- scripts/add_part.py
- scripts/parts.py
Per the Wed 2/27 telecon, I added the ability to look at all of the notes and to sort by dates.
> Implement ability to view all notes and to filter on dates

- scripts/mc_monitor_correlator.py
- scripts/mc_monitor_nodes.py
to try to prevent the kind of problem @dannyjacobs saw today
> Add more rollbacks to daemon scripts

- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
fixes a pending deprecation error.
> convert yaml.load to yaml.safe_load because of deprecation

- .gitignore
- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
- scripts/correlator_control.py
Better docstings, raise error if `acclen_spectra` isn't an integer multiple of 2048.
> Improve correlator command script

- hera_mc/tests/test_utils.py
- hera_mc/utils.py
- scripts/mc_monitor_correlator.py
- scripts/mc_monitor_nodes.py
This is an improvement of the monitor daemons so they should keep operating if there's an error.
> Modify MC daemons to handle errors better

- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
@dannyjacobs I think this should fix the root cause of the error you were seeing on qmaster.
> Add handling for 'None' timestamp in snap status

- scripts/mc_monitor_correlator.py
- scripts/mc_monitor_nodes.py
> add missing except to daemons

- Docs/time_conversion_function
I added this function to the site DB to make plotting easier on grafana
> epoch time conversion for grafana

- scripts/parts.py
Fixes the bug in parts.py pointed out in today's meeting.
> took out session positional call in cm_health

- alembic/versions/50c966c5427a_more_antenna_stats.py
- hera_mc/correlator.py
- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
- setup.py
> More antenna stats, use 1 hera_corr_cm object to limit redis connections

- hera_mc/correlator.py
- hera_mc/tests/test_correlator.py
> Handle -1s and other weird values in fem/pam IDs

- hera_mc/mc_session.py
> fix RunTimeError camelcase

- scripts/add_part.py
- scripts/add_station.py
The earlier PR introduced several name/etc changes that did not make it into all of the needed scripts.
> fixed scripts from earlier PR changes

- scripts/write_records_to_file.py
> remove erroneous dict entry from write_to_file

- hera_mc/weather.py
works on site.
weather data back-updated.
> update time attribute names

- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
@mkolopanis can you see if this does what you want?
> add get_snap_hostname_from_serial method

- .gitignore
- .travis.yml
- README.md
- hera_mc/tests/__init__.py
- hera_mc/tests/conftest.py
- hera_mc/tests/test_cm_transfer.py
- hera_mc/tests/test_cm_utils.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_daemon_status.py
- hera_mc/tests/test_dataview.py
- hera_mc/tests/test_db_check.py
- hera_mc/tests/test_default_db_schema.py
- hera_mc/tests/test_geo_location.py
- hera_mc/tests/test_librarian.py
- hera_mc/tests/test_node.py
- hera_mc/tests/test_observations.py
- hera_mc/tests/test_parts.py
- hera_mc/tests/test_qm.py
- hera_mc/tests/test_rtp.py
- hera_mc/tests/test_server_status.py
- hera_mc/tests/test_subsystem_error.py
- hera_mc/tests/test_sysutils.py
- hera_mc/tests/test_utils.py
- hera_mc/tests/test_version.py
- hera_mc/tests/test_weather.py
- scripts/test_cover_noinstall.sh
- scripts/test_coverage.sh
- setup.cfg
> convert nosetests to pytest

- scripts/geo.py
Adds a hookup-type option to geo plotting
> added hookup-type to geo

- scripts/add_rtp_process_record.py
adds a script for creating RTPProcessRecords from the command line for new makeflow based rtp
> RTP Processing Record script

- scripts/add_qm_metrics.py
removed some unnecessary code from the add_qm_metrics script and removed unused imports.
> Update add qm script

- scripts/mc_publish_summary.py
Removes some unused keywords in mc_publish_summary script since PR merges.
May need a test run on qmaster
closes #429
should close HERA-Team/HERA_Commissioning#302
> Update mc_publish_summary script

- hera_mc/cm_partconnect.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_parts.py
It is useful to have == and != work for parts and connections in checking for connection issues.
> added part and connection equality with tests

- hera_mc/tests/conftest.py
- hera_mc/tests/test_utils.py
Based on an improvement trialed recently in pyuvdata.
fixes #417
> Improve IERS handling for tests

- hera_mc/cm_sysutils.py
The show-hookup call had changed, which hadn't been reflected back to this sysutils call.
> updated publish_summary to new interface order

- hera_mc/cm_dossier.py
- hera_mc/tests/test_parts.py
- scripts/parts.py
This fixes the error in printing comment times (each "row" has multiple comments and times).
> Fix notes script

- .github/workflows/testsuite.yml
- README.md
- ci/tests.yaml
- hera_mc/tests/__init__.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_node.py
Adds the redis service to github for additional code validation. Makes new decorator `requires_redis` many `onsite` tests moved to `requires_redis` instead.
> GitHub redis

- README.md
Adds all the daemons needed restarting to Readme.
Slight reformatting of environments sectoin
> Add daemons to readme

- hera_mc/cm_redis_corr.py
- hera_mc/cm_sysutils.py
- hera_mc/tests/test_sysutils.py
This updates the cminfo that gets into redis by removing a few unused and adding antenna alts.
> Cminfo update

- hera_mc/cm_redis_corr.py
- hera_mc/cm_sysutils.py
- hera_mc/mc.py
- hera_mc/tests/test_db_check.py
- hera_mc/tests/test_sysutils.py
Made the discussed changes to cminfo.  Also fixed a goofy use of a dict in redis_corr_cm.
> made cminfo changes

- scripts/mc_monitor_daemons.py
Moving daemon monitoring over from corr_cm.
This script is almost and exact duplicate of the daemon_monitor from corr_cm with small formatting PEP changes and a larger try/catch loop for this daemon erroring.
> Mc monitor daemons

- ci/install_conda.sh
- hera_mc/correlator.py
- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
- scripts/correlator_control.py
Also add some explanatory inline comments to clarify how commands are actually called.
> Add 'hard_stop' and 'force' options to the correlator control interface

- .github/workflows/testsuite.yml
some formatting changes to the yaml, make it easier to read and use the built-in `::add-path::` feature in actions.
> Clean up GitHub actions yaml

- hera_mc/cm_sysdef.py
There wasn't a known error associated with this, but not very good to have the duplicates.
> change to not duplicate ports in sysdef

- scripts/add_part_info.py
- scripts/add_part_rosetta.py
This removes print statements so we don't get spammed by the cronjob mailer
> made info/rosetta scripts need a verbose to print

- hera_mc/cm_active.py
- hera_mc/tests/test_sysutils.py
- hera_mc/watch_dog.py
- scripts/wd_node_temp.py
This adds a watch dog to monitor node temperatures
> Weather dog

- hera_mc/cm_hookup.py
- hera_mc/cm_sysutils.py
Adds the reference field to the get_notes method in get_hookup:  {'notes': <note>, 'ref': <reference>}
This will close #512
> added reference to get_notes in cm_hookup

- hera_mc/cm_partconnect.py
- hera_mc/tests/test_connections.py
- scripts/update_part_rosetta.py
The script did not match the method.  I also stopped forcing the part number to upper.
> had to fix the rosetta script and removed force upper

- hera_mc/db_check.py
It seems that periodically hera_mc can't connect to the database
[
from nb:
OperationalError: (psycopg2.OperationalError) could not translate host name "qmaster" to address: No address associated with hostname
(Background on this error at: http://sqlalche.me/e/13/e3q8)
]
This tries to connect twice with 5 sec breaks in between.
> added operationalError check in valid_db method

- .github/workflows/testsuite.yml
updated github actions add-path and set-env to use new non-deprecated syntax
> update add-path to use new syntax

- hera_mc/mc_session.py
- hera_mc/tests/test_node.py
These are fixes following the merge of PR #518 which led to both code errors and testing errors onsite. 
Tests pass with these fixes.
> Fix bugs in code and tests that were causing code and tests to fail onsite

- README.md
Add pots 1 & 6 as machines to reinstall on, add helpful details for restarting daemons.
> update the readme to better document the site updating procedure

- README.md
The link to mc_definition in the README was incorrect.
> change directory from docs to Docs

- README.md
This is a small PR to make the installation instructions for updating on-site reflect current reality.
> Update readme to reflect latest installation instructions

- hera_mc/db_check.py
Fix errors seen with new release of sqlalchemy (v1.4).
Closes #546
> Future proof the db_check code by ensuring that it uses only the sqlalchemy public API.

- hera_mc/cm_gen_sqlite.py
- hera_mc/data/test_data/inserts.sql
- hera_mc/data/test_data/schema.sql
- hera_mc/tests/test_cm_transfer.py
- scripts/write_sqlite.py
The sqlite stuff was in the cm updates repo, which is not where it should be.  This moves it to hera_mc and adds testing.
> Moves conversion to sqlite to this repo.

- .github/workflows/testsuite.yml
pins codecov at v1.5.2 until codecov/codecov-action#372 is resolved
> pin codecov action version

- hera_mc/cm_transfer.py
- hera_mc/mc_session.py
- hera_mc/tests/test_qm.py
- hera_mc/tests/test_sysutils.py
- hera_mc/tests/test_utils.py
- hera_mc/utils.py
The keywords in these methods behaved very differently than the other get methods in mc_session.py, this PR standardizes them.
> standardize the keywords in the `get_*_metric` methods

- scripts/mc_launch_rtp.py
Updates the RTP launch script to skip to the next JD waiting if there is an error. Also replaces screen with tmux because paul and I like it better than screen.
TODO:
> Update rtp launch

- hera_mc/tests/test_sysutils.py
- hera_mc/watch_dog.py
For another reason I updated the smtplib mailer to use EmailMessage instead of strings, which is finicky.
> change watch dog to use EmailMessage and update tests

- .github/workflows/testsuite.yml
- ci/min_deps.yaml
- ci/tests.yaml
- hera_mc/tests/__init__.py
- hera_mc/tests/test_autocorrelations.py
- hera_mc/tests/test_cm_transfer.py
- hera_mc/tests/test_connections.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_node.py
- hera_mc/tests/test_parts.py
- hera_mc/tests/test_qm.py
- hera_mc/tests/test_sysutils.py
- hera_mc/tests/test_weather.py
- hera_mc/weather.py
- setup.py
Also added testing against 3.10, drop testing agains python 3.6.
> Add a CI job to ensure tests pass with only the required dependencies installed

- hera_mc/correlator.py
I hadn't updated the docstring...
> took out the fem_e_/fem_n_ thing to just be fem_

- hera_mc/correlator.py
Currently installed on qmaster
> Added float cast in correlator.py for adc_power

- hera_mc/correlator.py
- hera_mc/tests/test_correlator.py
This will hopefully make this more robust in terms of getting meaningful id numbers into the database.
> Get pam_id and fem_id into database

- alembic/versions/d2f22cbd4c5a_add_ant_metric_indices.py
- hera_mc/qm.py
To speed up a query for @dannyjacobs.
> Add indices for more ant_metrics columns

- CHANGELOG.md
- README.md
- setup.py
Fixes to allow the hera_mc package to be uploaded to pypi and for links in the description there to work (tested on testpypi).
I couldn't properly test this until we made a new release. Upon testing, I found that it errored because it was expecting an RST description instead of markdown. I fixed that and also fixed some links that were broken (I tested this on testpypi by adding local git tags to my repo so that I could simulate versions. I should have thought of doing that before but didn't).
To see how it appears on testpypi follow this link: https://test.pypi.org/project/hera-mc/
> minor description fixes for pypi

- .github/workflows/publish-to-test-pypi.yml
- ci/publish.yml
> Add a workflow to publish releases to pypi

- hera_mc/mc_session.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_node.py
- hera_mc/watch_dog.py
- setup.py
changes the default node address from `None` to `node.defaultServerAddress` in mc_session
None was pointing to `localhost` which is not where redis is located.
> update default node redis address

- docs/developer.md
- hera_mc/watch_dog.py
a-yet-nother redis dump update, expiry removed.
I've also added some more on the developer docs about running redis on a development environment and updating redis save files. 
Please let me know if you want more text.
> Update redis dump

- CHANGELOG.md
Changelog updates for version 3.0.
We just merged in a major API change for the configuration management.
> update the changelog for the new version

- scripts/add_rtp_task_resource_records.py
Updated `add_rtp_task_resource_records.py` to account for RTP jobs submitted with multiple attempts.  Also fixed a bug in the SLURM query related to parsing a string with a fixed column width.
Fixes broken `add_rtp_task_resource_records.py` script.
> Fix rtp resource records

- scripts/hera_mini_snap_data_catcher.py
Adds a mini data catcher script to save snap spectra to a UVH5 file.
Reads the `status:snap:*` keys in redis and compiles them into a UVData object to save to disk.
Danny asked for this.
Other:
> Add snap mini corr

- hera_mc/mc_session.py
- scripts/write_records_to_file.py
Update the write_records_to_file script to include more tables and more filter columns.
> Update write_records_to_file script to support more tables

- scripts/mc_launch_rtp.py
Changes the location of the makeflow toml for H6C
Schema change:
Other:
> Update mc_launch_rtp for h6c

- hera_mc/observations.py
We recently added a column to the observation table that effectively enforces an enum for particular tag values. The "maintenance" column value had a typo, so this corrects that.
Other:
> Fix typo in column name

- .github/PULL_REQUEST_TEMPLATE.md
- docs/site_operations.md
- Add a checkbox for updating monitoring scripts when schema changes if appropriate
- Add reminder about using `--no-deps` for onsite installs.
Other:
> docs improvements

- scripts/hera_mini_snap_data_catcher.py
have the mini catcher sleep longer. Snap autos don't update very often anyway
> Add longer sleep to mini catcher

- hera_mc/mc_session.py
to avoid duplicate key bug we are seeing now onsite.
Schema change:
Other:
> add correlator config status with ignoring duplicates

- daemons/correlator_status.systemd
- daemons/mc_listen_to_corr_logger.systemd
- daemons/mc_monitor_daemons.systemd
- daemons/node_status.systemd
- daemons/server-status.systemd
- daemons/server-status.upstart
Update the daemons to point at the correct environments.
Other:
> update daemons for new environments

- scripts/mc_launch_rtp.py
> Use new version of RTP with file_calibration notebook

- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/testsuite.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- alembic/versions/3e86ac6195d8_increase_size_of_lib_files_filename.py
- alembic/versions/5b141f32ea38_remove_bad_autoincrements.py
- alembic/versions/5feda4ca9935_add_rtp_task_multiple_process_event_table.py
- alembic/versions/9d9af47e64c8_add_rtptaskprocessevent_table.py
- alembic/versions/b1063869f198_bring_up_to_master.py
- alembic/versions/c0985153bf41_add_cm_version_table.py
- ci/publish.yml
- hera_mc/__init__.py
- hera_mc/cm_sysutils.py
- hera_mc/cm_transfer.py
- hera_mc/cm_utils.py
- hera_mc/db_check.py
- hera_mc/geo_handling.py
- hera_mc/tests/conftest.py
- hera_mc/tests/test_cm_utils.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_db_check.py
- hera_mc/tests/test_sysutils.py
- setup.py
SQLAlchemy 2.0 is out and it broke some things. This PR fixes:
- compatibility with SQLAlchemy 2.0
- Some old problems in alembic revisions that prevented upgrades and downgrades from being fully reversible.
- Adds a new CI that runs the tests with the `-W error` flag to catch warnings. As on other repos, I don't think this should be a required check, but it will prevent us missing new deprecation warnings (as we did with the changes in SQLAlchemy 2.0 which were warned about for some time apparently).
- Drop support for python 3.7.
- Fixes conftest and cm_utils.py to make it possible to run tests from another folder. Runs from another folder in the min_deps test to improve coverage in `__init__.py`
> Fix compatibility with sqlalchemy2.0

- hera_mc/db_check.py
- hera_mc/geo_handling.py
Add filters for numpy warnings generated in cartopy calls. These should be removed when carroty is updated to fix them.
Fix CI errors blocking other PRs.
Other:
> Add filters for numpy warnings generated in cartopy calls

- scripts/mc_launch_rtp.py
- scripts/mc_launch_rtp_daemon.py
> Update mc_launch_rtp.py for H7C

- scripts/mc_launch_rtp_daemon.py
> also delete diff.dat files

- scripts/hera_mini_snap_data_catcher.py
- scripts/mc_launch_rtp_daemon.py
updates the snap auto catcher script to more properly set the phase center catalog. Was exploiting some old phase code before.
> more properly set phase info for the snap auto UVData object

- scripts/mc_launch_rtp_daemon.py
> update launch daemon for h8c

- daemons/mc_monitor_daemons.systemd
- daemons/server-status.systemd
- docs/site_operations.md
- hera_mc/cm_sysutils.py
- hera_mc/tests/test_correlator.py
- hera_mc/tests/test_sysutils.py
Various fixes that have lived for some time on site but never been pushed up to GitHub.
local changes on site are bad!
Other:
> various fixes from site
